# basic options
title: Jasim Azizi
author: admin
email: your-email@domain.com
description: A wonderful site
twitter_username: jasim-azizi
github_username:  jasimazizi

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
